name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker image to ACR for AppService CD.
        id: build-image
        run: |
          # Build a docker container and
          # push it to ACR
          docker login -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} ${{ secrets.AZURE_ACR_URL }}
          docker build -t ${{ secrets.AZURE_ACR_URL }}/brendantimmons-com:latest .
          docker push ${{ secrets.AZURE_ACR_URL }}/brendantimmons-com:latest
